"""
SEC-10: Model file integrity verification.

Verifies SHA-256 checksums of all pickled ML model files at startup to guard
against supply-chain tampering or accidental corruption.

Usage
-----
1. Generate checksums once (after training / committing models):

       python -c "from app.utils.model_integrity import generate_checksums; generate_checksums()"

   This writes ``app/models/checksums.sha256``.

2. At server startup call :func:`verify_all_models`. It raises
   ``ModelIntegrityError`` if any model file is missing or has the wrong hash.

The checksum file is a plain text file (one line per model):
    <hex-sha256>  <relative-path-from-models-dir>

This format is compatible with ``sha256sum -c`` on Linux/macOS for manual
verification outside Python.
"""

import hashlib
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT_DIR = Path(__file__).resolve().parents[2]
MODELS_DIR = ROOT_DIR / "app" / "models"
LEGACY_MODELS_DIR = ROOT_DIR / "models"
CHECKSUM_FILE = MODELS_DIR / "checksums.sha256"

# Model files that MUST pass integrity checks.
# Filenames are resolved against app/models first, then backend-python/models.
_REQUIRED_MODEL_FILES = [
    # Canonical app/models artifacts
    "xgb_workout.pkl",
    "xgb_meal.pkl",
    "le_gender.pkl",
    "le_goal.pkl",
    "le_target.pkl",
    # Decomposition models used in normal production inference paths
    "xgboost_volume.pkl",
    "xgboost_intensity.pkl",
    "xgboost_split.pkl",
    "xgboost_frequency.pkl",
    "xgboost_sets.pkl",
    "xgboost_reps.pkl",
    "xgboost_rest.pkl",
    "xgboost_progression.pkl",
    # Legacy encoder / model filenames still referenced by older trainers/loaders
    "goal_encoder.pkl",
    "label_encoder_experience.pkl",
    "meal_model.pkl",
    "workout_model.pkl",
]

# Optional model artifacts. If missing, app can safely fall back to other models.
_OPTIONAL_MODEL_FILES = [
    "multi_output_xgboost_model.joblib",
]


class ModelIntegrityError(RuntimeError):
    """Raised when a model file fails its SHA-256 check."""


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------

def _sha256_file(path: Path) -> str:
    """Return the hex SHA-256 digest of *path* (streaming, memory-safe)."""
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _resolve_model_path(filename: str) -> Path:
    """Resolve filename from canonical models dir, then legacy fallback dir."""
    primary = MODELS_DIR / filename
    if primary.exists():
        return primary

    legacy = LEGACY_MODELS_DIR / filename
    if legacy.exists():
        return legacy

    return primary


def _load_checksums() -> dict[str, str]:
    """Parse ``checksums.sha256`` → ``{filename: expected_hex}``."""
    if not CHECKSUM_FILE.exists():
        return {}
    result: dict[str, str] = {}
    with CHECKSUM_FILE.open() as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(None, 1)
            if len(parts) == 2:
                hex_digest, rel_path = parts
                # Strip leading "./" if present (sha256sum compat)
                result[rel_path.lstrip("./")] = hex_digest
    return result


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_checksums() -> None:
    """
    Compute and write SHA-256 hashes for all model files to
    ``app/models/checksums.sha256``.

    Run this once after training and commit the checksum file to source
    control so that future deployments can verify integrity automatically.
    """
    lines = [
        "# Elevate ML model checksums — generated by model_integrity.py",
        "# Format: <sha256hex>  <filename>",
        "# Files resolve from app/models first, then backend-python/models.",
        "",
    ]
    for rel in _REQUIRED_MODEL_FILES + _OPTIONAL_MODEL_FILES:
        path = _resolve_model_path(rel)
        if path.exists():
            digest = _sha256_file(path)
            lines.append(f"{digest}  {rel}")
            logger.info("Checksum OK: %s  %s", digest[:16] + "…", rel)
        else:
            logger.warning("Model file not found, skipping: %s", rel)

    CHECKSUM_FILE.parent.mkdir(parents=True, exist_ok=True)
    CHECKSUM_FILE.write_text("\n".join(lines) + "\n")
    print(f"[model_integrity] Checksums written to {CHECKSUM_FILE}")


def verify_all_models(strict: bool = True) -> dict[str, str]:
    """
    Verify SHA-256 checksums for required model files and best-effort optional ones.

    Parameters
    ----------
    strict : bool
        If ``True`` (default) raise :class:`ModelIntegrityError` on any
        failure.  If ``False`` log errors but continue — useful for dev.

    Returns
    -------
    dict
        ``{filename: 'ok' | 'missing' | 'mismatch' | 'no_checksum' | 'optional_missing'}``
    """
    expected = _load_checksums()
    results: dict[str, str] = {}
    failures: list[str] = []

    for rel in _REQUIRED_MODEL_FILES:
        path = _resolve_model_path(rel)

        if not path.exists():
            msg = f"Model file missing: {rel}"
            logger.error("[SEC-10] %s", msg)
            results[rel] = "missing"
            failures.append(msg)
            continue

        if rel not in expected:
            # No checksum recorded yet — warn but don't fail hard in dev.
            logger.warning(
                "[SEC-10] No checksum on record for %s — run generate_checksums()", rel
            )
            results[rel] = "no_checksum"
            continue

        actual = _sha256_file(path)
        if actual == expected[rel]:
            results[rel] = "ok"
            logger.debug("[SEC-10] Integrity OK: %s", rel)
        else:
            msg = (
                f"Checksum mismatch for {rel}: "
                f"expected {expected[rel][:16]}… got {actual[:16]}…"
            )
            logger.error("[SEC-10] %s", msg)
            results[rel] = "mismatch"
            failures.append(msg)

    # Optional models are validated when present, but do not fail startup when missing.
    for rel in _OPTIONAL_MODEL_FILES:
        path = _resolve_model_path(rel)

        if not path.exists():
            logger.info("[SEC-10] Optional model missing: %s (fallback path will be used)", rel)
            results[rel] = "optional_missing"
            continue

        if rel not in expected:
            logger.warning(
                "[SEC-10] No checksum on record for optional model %s — run generate_checksums()", rel
            )
            results[rel] = "no_checksum"
            continue

        actual = _sha256_file(path)
        if actual == expected[rel]:
            results[rel] = "ok"
            logger.debug("[SEC-10] Integrity OK: %s", rel)
        else:
            msg = (
                f"Checksum mismatch for optional model {rel}: "
                f"expected {expected[rel][:16]}… got {actual[:16]}…"
            )
            logger.warning("[SEC-10] %s", msg)
            results[rel] = "mismatch"

    if failures and strict:
        raise ModelIntegrityError(
            "ML model integrity check failed:\n" + "\n".join(f"  • {f}" for f in failures)
        )

    return results


def verify_single_model(rel_path: str) -> bool:
    """
    Convenience wrapper — verify one model file and return True/False.
    Does NOT raise; callers decide how to handle the result.
    """
    expected = _load_checksums()
    path = _resolve_model_path(rel_path)

    if not path.exists():
        logger.error("[SEC-10] Model file missing: %s", rel_path)
        return False

    if rel_path not in expected:
        logger.warning("[SEC-10] No checksum recorded for %s", rel_path)
        return True  # Treat as OK until checksums are generated

    actual = _sha256_file(path)
    ok = actual == expected[rel_path]
    if not ok:
        logger.error("[SEC-10] Checksum mismatch: %s", rel_path)
    return ok
