import os
import sys
import random

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.meal_engine import MealEngine

def generate_profiles(count=100):
    goals = ['Fat Loss', 'Muscle Gain', 'Maintenance']
    diets = ['Veg', 'Vegan', 'Non-Veg']
    regions = ['pan_indian', 'north_indian', 'south_indian']
    genders = ['Male', 'Female']
    activity_levels = ['Sedentary', 'Light', 'Moderate', 'Active', 'Very Active']
    
    profiles = []
    for i in range(count):
        profiles.append({
            'weight': random.randint(55, 95),
            'height': random.randint(155, 190),
            'age': random.randint(20, 50),
            'gender': random.choice(genders),
            'activity_level': random.choice(activity_levels),
            'goal': random.choice(goals),
            'dietary_preference': random.choice(diets),
            'region': random.choice(regions),
            'allergies': []
        })
    return profiles

def main():
    print("Initializing MealEngine...")
    engine = MealEngine()
    
    print("Generating profiles...")
    profiles = generate_profiles(100)
    
    md_content = []
    md_content.append("# Weekly Meal Plan Gallery")
    md_content.append("This gallery contains 100 complete weekly meal plans generated by the Elevate Nutrition Engine (V6).\n")
    
    # Generate Index
    md_content.append("## Index of Plans")
    for idx, p in enumerate(profiles):
        link_title = f"Plan {idx+1}: {p['goal']} ({p['dietary_preference']}, {p['region'].replace('_', ' ').title()})"
        link_anchor = link_title.lower().replace(":", "").replace("(", "").replace(")", "").replace(",", "").replace(" ", "-")
        md_content.append(f"- [{link_title}](#{link_anchor})")
    md_content.append("\n---\n")
    
    for idx, p in enumerate(profiles):
        print(f"Generating Plan {idx+1}/100...")
        
        link_title = f"Plan {idx+1}: {p['goal']} ({p['dietary_preference']}, {p['region'].replace('_', ' ').title()})"
        md_content.append(f"## {link_title}")
        md_content.append(f"**User Profile**: {p['gender']}, {p['age']} years old, {p['weight']}kg, {p['height']}cm")
        md_content.append(f"**Goal**: {p['goal']} | **Activity Level**: {p['activity_level']}")
        
        try:
            # Generate plan
            res = engine.generate_meal_plan(p)
            weekly_plan = res.get('weekly_plan', {})
            targets = res.get('daily_targets_by_day', {})
            
            # Print daily target metrics average
            avg_cal = 0
            avg_prot = 0
            avg_carbs = 0
            avg_fat = 0
            num_days = len(targets)
            if num_days > 0:
                avg_cal = sum(t['calories'] for t in targets.values()) / num_days
                avg_prot = sum(t['protein'] for t in targets.values()) / num_days
                avg_carbs = sum(t['carbs'] for t in targets.values()) / num_days
                avg_fat = sum(t['fat'] for t in targets.values()) / num_days
                
            md_content.append(f"**Target Daily Average**: {avg_cal:.0f} kcal (Protein: {avg_prot:.1f}g, Carbs: {avg_carbs:.1f}g, Fat: {avg_fat:.1f}g)\n")
            
            for day, meals in weekly_plan.items():
                md_content.append(f"### {day}")
                day_target = targets.get(day, {})
                md_content.append(f"*Day Target: {day_target.get('calories', 0)} kcal, Protein: {day_target.get('protein', 0)}g, Carbs: {day_target.get('carbs', 0)}g, Fat: {day_target.get('fat', 0)}g*")
                
                for mt in ['breakfast', 'lunch', 'snack', 'dinner']:
                    items = meals.get(mt, [])
                    if not items:
                        md_content.append(f"* **{mt.capitalize()}**: (No foods recommended)")
                        continue
                        
                    item_strs = []
                    meal_cal = 0.0
                    meal_prot = 0.0
                    meal_carbs = 0.0
                    meal_fat = 0.0
                    
                    for item in items:
                        serving = item.get('serving', '')
                        name = item.get('food_name', '')
                        
                        item_cal = float(item.get('calories', 0))
                        item_prot = float(item.get('protein', 0))
                        item_carbs = float(item.get('carbs', 0))
                        item_fat = float(item.get('fat', 0))
                        
                        meal_cal += item_cal
                        meal_prot += item_prot
                        meal_carbs += item_carbs
                        meal_fat += item_fat
                        
                        item_strs.append(f"{name} ({serving})")
                        
                    items_desc = ", ".join(item_strs)
                    md_content.append(f"* **{mt.capitalize()}**: {items_desc} | *{meal_cal:.0f} kcal, P: {meal_prot:.1f}g, C: {meal_carbs:.1f}g, F: {meal_fat:.1f}g*")
                md_content.append("")
                
        except Exception as e:
            md_content.append(f"**FAILED TO GENERATE PLAN**: {e}\n")
            
        md_content.append("\n---\n")
        
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "weekly_plans_gallery.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_content))
    print(f"Gallery written to {out_path}")

if __name__ == "__main__":
    main()
