import logging
from typing import Dict, List, Any
import math

logger = logging.getLogger(__name__)

class MealScorer:
    """
    Semantic Meal Scorer (Phase 4.6).
    Evaluates complete meal candidates generated by the CandidateGenerator.
    """
    def __init__(self, variety_tracker=None):
        self.variety_tracker = variety_tracker
        
        # New Scoring Weights based on user specifications
        self.WEIGHT_MACRO = 0.25
        self.WEIGHT_SEMANTICS = 0.20
        self.WEIGHT_COMPLETENESS = 0.15
        self.WEIGHT_REALISM = 0.15
        self.WEIGHT_VARIETY = 0.15
        self.WEIGHT_PORTION = 0.05
        self.WEIGHT_BUDGET = 0.05

    def score_candidate_plate(self, plate: List[Dict], target_macros: Dict, current_day: int) -> Dict[str, Any]:
        """
        Scores a plate against macros, semantics, and realism.
        Returns a dictionary with the total score and a breakdown.
        """
        if not plate:
            return {"total_score": 0, "breakdown": {}}
            
        # 1. Macro Accuracy (25%)
        macro_score = self._score_macros(plate, target_macros)
        
        # 2. Semantic Compatibility (25%)
        semantic_score = self._score_semantics(plate)
        
        # 3. Meal Completeness (15%)
        # In this implementation, the Candidate Generator ensures required roles exist.
        # But we can reward having preferred optional items.
        completeness_score = self._score_completeness(plate)
        
        # 4. Realism & Satisfaction (15%)
        realism_score = self._score_realism(plate)
        
        # 5. Weekly Variety (10%)
        variety_score = self._score_variety(plate, current_day)
        
        # 6. Portion Realism (5%)
        portion_score = self._score_portion(plate)
        
        # 7. Budget & Availability (5%) - Stubbed for future expansion
        budget_score = 100
        
        total_score = (
            (macro_score * self.WEIGHT_MACRO) +
            (semantic_score * self.WEIGHT_SEMANTICS) +
            (completeness_score * self.WEIGHT_COMPLETENESS) +
            (realism_score * self.WEIGHT_REALISM) +
            (variety_score * self.WEIGHT_VARIETY) +
            (portion_score * self.WEIGHT_PORTION) +
            (budget_score * self.WEIGHT_BUDGET)
        )
        
        return {
            "total_score": round(total_score, 2),
            "breakdown": {
                "macro_score": round(macro_score, 2),
                "semantic_score": round(semantic_score, 2),
                "completeness_score": round(completeness_score, 2),
                "realism_score": round(realism_score, 2),
                "variety_score": round(variety_score, 2),
                "portion_score": round(portion_score, 2),
                "budget_score": round(budget_score, 2)
            }
        }

    def _score_macros(self, plate: List[Dict], target: Dict) -> float:
        total_p = sum(node['nutrition']['protein'] for node in plate)
        total_c = sum(node['nutrition']['carbs'] for node in plate)
        total_f = sum(node['nutrition']['fat'] for node in plate)
        total_cal = sum(node['nutrition']['calories'] for node in plate)
        
        if target.get('calories', 0) <= 0:
            return 100.0
            
        # Standard deviation approach from target
        cal_diff = abs(total_cal - target['calories']) / target['calories']
        p_diff = abs(total_p - target['protein']) / target['protein'] if target['protein'] > 0 else 0
        
        # Convert diff to a 0-100 score (10% diff = 90 score)
        score = 100 - ((cal_diff * 0.6 + p_diff * 0.4) * 100)
        return max(0.0, min(100.0, score))

    def _score_semantics(self, plate: List[Dict]) -> float:
        if len(plate) <= 1:
            return 100.0 # Single item is inherently compatible with itself
            
        anchor = plate[0] # The candidate generator puts the anchor first
        total_comp = 0
        comparisons = 0
        
        for item in plate[1:]:
            role = item['semantics'].get('meal_role', 'unknown')
            comp = anchor.get('compatibility', {}).get(role, 50)
            total_comp += comp
            comparisons += 1
            
        return total_comp / comparisons if comparisons > 0 else 50.0

    def _score_completeness(self, plate: List[Dict]) -> float:
        # Give higher score if the plate has 2-4 items, signifying a complete meal
        # (This is a simplified completeness check)
        length = len(plate)
        if length == 1:
            return 50.0
        elif length == 2:
            return 80.0
        elif 3 <= length <= 4:
            return 100.0
        else:
            return 90.0

    def _score_realism(self, plate: List[Dict]) -> float:
        score = 100.0
        roles = [node['semantics'].get('meal_role') for node in plate]
        
        # Penalize weird combinations
        if roles.count('protein_main') > 1:
            score -= 40 # Two heavy mains
        if roles.count('beverage') > 1:
            score -= 30 # Two drinks
        if roles.count('salad') > 1:
            score -= 20 # Two salads
            
        # Penalize if it only contains side dishes
        if 'protein_main' not in roles and 'carb_base' not in roles and 'combo_meal' not in roles:
            score -= 50
            
        # Texture/Temperature variety
        styles = [node['semantics'].get('cooking_style', 'Mixed') for node in plate]
        if 'Soup' in styles and 'Salad' in styles:
            score += 10  # Good contrast
        if styles.count('Dry') > 2:
            score -= 20  # Too dry
            
        # Phase 5: Meal Satisfaction Heuristics
        food_names_lower = [str(node.get('food_name', '')).lower() for node in plate]
        
        # 1. Curries/Gravy pair wonderfully with Carb bases
        if 'Gravy' in styles or 'Curry' in styles or any('curry' in fn or 'dal' in fn for fn in food_names_lower):
            if 'carb_base' in roles or any('rice' in fn or 'roti' in fn or 'chapati' in fn or 'paratha' in fn for fn in food_names_lower):
                score += 15
                
        # 2. Dry dishes need Dal, Raita, or Chutney to not feel too dry
        if styles.count('Dry') > 0 or any('dry' in fn or 'tikk' in fn for fn in food_names_lower):
            if 'dairy_side' in roles or 'salad' in roles or 'Soup' in styles or any('raita' in fn or 'chutney' in fn or 'dal' in fn for fn in food_names_lower):
                score += 10
            else:
                score -= 10
                
        # 3. Protein pairing satisfaction (e.g. Eggs + Bread)
        if any('egg' in fn for fn in food_names_lower) and any('bread' in fn or 'toast' in fn for fn in food_names_lower):
            score += 10
            
        # Satiety / Volume density heuristic
        # If total volume is high but calories are low, good for weight loss
        total_fiber = sum(node['nutrition'].get('fiber', 0) for node in plate)
        if total_fiber > 10:
            score += 10
        elif total_fiber == 0:
            score -= 10
            
        return max(0.0, min(100.0, score))

    def _score_variety(self, plate: List[Dict], current_day: int) -> float:
        if not self.variety_tracker:
            return 100.0
            
        score = 100.0
        shopping_efficiency_bonus = 0.0
        
        for node in plate:
            family = node['semantics'].get('family')
            food_name = node.get('food_name', '')
            
            penalty = self.variety_tracker.calculate_variety_penalty(node.get('food_id', ''), family, current_day)
            score -= (penalty * 10)
            
            # Grocery reuse (Shopping Efficiency)
            # If the food was eaten on previous days, it's efficient to reuse groceries
            # But we don't want it every day (which is penalized by variety)
            # A sweet spot is 1-2 days ago.
            past_days = [d for d, foods in self.variety_tracker.daily_food_history.items() if d < current_day and food_name.lower().strip() in foods]
            if past_days:
                shopping_efficiency_bonus += 5.0
                
        # Shopping efficiency caps out at 20
        score += min(20.0, shopping_efficiency_bonus)
            
        return max(0.0, min(100.0, score))

    def _score_portion(self, plate: List[Dict]) -> float:
        score = 100.0
        for node in plate:
            unit = node.get('serving_unit', 'g')
            qty = float(node.get('serving_qty', 1.0))
            
            # Penalize absurd quantities for realistic units
            if unit in ('slice', 'slices') and qty > 4:
                score -= 20
            if unit in ('bowl', 'bowls') and qty > 3:
                score -= 30
            if unit in ('piece', 'pieces', 'unit') and qty > 6:
                score -= 20
                
        return max(0.0, min(100.0, score))
