import logging
from typing import Dict, List, Any
import math
from app.nutrition_engine.config import NUTRITION_RULES

logger = logging.getLogger(__name__)

class MealScorer:
    """
    Semantic Meal Scorer (Phase 4.6).
    Evaluates complete meal candidates generated by the CandidateGenerator.
    """
    def __init__(self, variety_tracker=None):
        self.variety_tracker = variety_tracker
        
        # New Scoring Weights based on user specifications: 60% Nutrition, 40% Culinary
        self.WEIGHT_MACRO = 0.60
        self.WEIGHT_SEMANTICS = 0.10
        self.WEIGHT_COMPLETENESS = 0.05
        self.WEIGHT_REALISM = 0.10
        self.WEIGHT_VARIETY = 0.10
        self.WEIGHT_PORTION = 0.05
        self.WEIGHT_BUDGET = 0.00

    def score_candidate_plate(self, plate: List[Dict], target_macros: Dict, current_day: int, meal_type: str = "unknown", goal: str = "Maintenance", previous_meals: List = None, preferred_region: str = None) -> Dict[str, Any]:
        """
        Scores a plate against macros, semantics, and realism.
        Returns a dictionary with the total score and a breakdown.
        """
        if not plate:
            return {"total_score": 0, "breakdown": {}}
            
        # 1. Macro Accuracy (25%)
        macro_score = self._score_macros(plate, target_macros, goal)
        
        # 2. Semantic Compatibility (25%)
        semantic_score = self._score_semantics(plate)
        
        # 3. Meal Completeness (15%)
        # In this implementation, the Candidate Generator ensures required roles exist.
        # But we can reward having preferred optional items.
        completeness_score = self._score_completeness(plate)
        
        # 4. Realism & Satisfaction (15%)
        realism_score = self._score_realism(plate)
        
        # 5. Weekly Variety (10%)
        variety_score = self._score_variety(plate, current_day, meal_type)
        
        # 6. Portion Realism (5%)
        portion_score = self._score_portion(plate)
        
        # 7. Budget & Availability (5%) - Stubbed for future expansion
        budget_score = 100.0

        # 8. Regional Score (Phase 7 preference boost)
        reg_cfg = NUTRITION_RULES.get("regional_preferences", {})
        default_pref = reg_cfg.get("default_region", "Maharashtra")
        from app.nutrition_engine.food_graph import normalize_cuisine_name
        pref_reg = normalize_cuisine_name(preferred_region or default_pref or "Maharashtrian").lower().strip()
        
        priority_list = [normalize_cuisine_name(c).lower().strip() for c in reg_cfg.get("cuisine_priority", [])]
        
        item_scores = []
        for item in plate:
            _rc = item.get("semantics", {}).get("regional_cuisine", "Pan Indian")
            item_region = (str(_rc.get("primary", "Pan Indian")) if isinstance(_rc, dict) else str(_rc)).lower().strip()
            
            # Map aliases for Pan Indian / All India
            if item_region in ("pan indian", "pan_indian", "all india", "all_india"):
                item_region = "pan indian"
                
            if item_region == pref_reg:
                item_scores.append(100.0)
            elif item_region in priority_list:
                idx = priority_list.index(item_region)
                score = max(40.0, 100.0 - idx * 15.0)
                item_scores.append(score)
            elif item_region == "pan indian":
                item_scores.append(80.0)
            else:
                item_scores.append(40.0)
                
        regional_score = sum(item_scores) / len(item_scores)
        
        # 60% nutrition / 40% culinary weight distribution
        nutrition_score = macro_score
        culinary_score = (
            (semantic_score * 0.08) +
            (completeness_score * 0.04) +
            (realism_score * 0.08) +
            (variety_score * 0.08) +
            (portion_score * 0.04) +
            (regional_score * 0.08)
        ) / 0.40
        
        total_score = (nutrition_score * 0.60) + (culinary_score * 0.40)
        
        logger.debug(
            f"Meal Score | Day {current_day} | {meal_type} | Goal: {goal} | "
            f"Macro: {macro_score:.1f}, Sem: {semantic_score:.1f}, "
            f"Comp: {completeness_score:.1f}, Real: {realism_score:.1f}, "
            f"Var: {variety_score:.1f}, Port: {portion_score:.1f}, Reg: {regional_score:.1f} -> Total: {total_score:.1f}"
        )
        
        return {
            "total_score": round(total_score, 2),
            "breakdown": {
                "macro_score": round(macro_score, 2),
                "semantic_score": round(semantic_score, 2),
                "completeness_score": round(completeness_score, 2),
                "realism_score": round(realism_score, 2),
                "variety_score": round(variety_score, 2),
                "portion_score": round(portion_score, 2),
                "regional_score": round(regional_score, 2),
                "budget_score": round(budget_score, 2)
            }
        }

    def score_culinary(self, plate: List[Dict], current_day: int) -> float:
        """
        Fast evaluation of the aesthetic/culinary value of a plate.
        Does not require macro portions to be optimized.
        """
        if not plate:
            return 0.0
            
        semantic_score = self._score_semantics(plate)
        completeness_score = self._score_completeness(plate)
        realism_score = self._score_realism(plate)
        variety_score = self._score_variety(plate, current_day)
        
        # We re-weight this to be out of 100 based on the weights used in score_candidate_plate
        # The culinary weights sum to 0.40 (10 + 5 + 10 + 10 + 5 portion)
        # We'll just sum them up directly using the same weights to keep relative scoring intact.
        total_culinary = (
            (semantic_score * self.WEIGHT_SEMANTICS) +
            (completeness_score * self.WEIGHT_COMPLETENESS) +
            (realism_score * self.WEIGHT_REALISM) +
            (variety_score * self.WEIGHT_VARIETY)
        )
        return total_culinary

    def _score_macros(self, plate: List[Dict], target: Dict, goal: str) -> float:
        total_p = sum(node['nutrition'].get('protein', 0) for node in plate)
        total_c = sum(node['nutrition'].get('carbs', 0) for node in plate)
        total_f = sum(node['nutrition'].get('fat', 0) for node in plate)
        total_cal = sum(node['nutrition'].get('calories', 0) for node in plate)
        
        cal_target = target.get('calories', 0)
        pro_target = target.get('protein', 0)
        carb_target = target.get('carbs', 0)
        fat_target = target.get('fat', 0)

        if cal_target <= 0:
            return 100.0
            
        cal_diff = abs(total_cal - cal_target) / max(cal_target, 1)
        p_diff = abs(total_p - pro_target) / max(pro_target, 1)
        c_diff = abs(total_c - carb_target) / max(carb_target, 1) if carb_target > 0 else 0.0
        f_diff = abs(total_f - fat_target) / max(fat_target, 1) if fat_target > 0 else 0.0

        # Goal-aware continuous macro scoring
        if goal == "Weight Loss":
            w_cal, w_pro, w_carb, w_fat = 0.45, 0.30, 0.15, 0.10
        elif goal == "Muscle Gain":
            w_cal, w_pro, w_carb, w_fat = 0.25, 0.45, 0.20, 0.10
        else: # Maintenance
            w_cal, w_pro, w_carb, w_fat = 0.35, 0.30, 0.20, 0.15

        # Normalize weights if some macros are omitted in target
        denom = w_cal + w_pro
        if carb_target > 0:
            denom += w_carb
        if fat_target > 0:
            denom += w_fat
            
        w_cal /= denom
        w_pro /= denom
        w_carb = w_carb / denom if carb_target > 0 else 0.0
        w_fat = w_fat / denom if fat_target > 0 else 0.0

        # Convert diff to a 0-100 score
        score = 100 - ( (cal_diff * w_cal + p_diff * w_pro + c_diff * w_carb + f_diff * w_fat) * 100 )
        return max(0.0, min(100.0, score))

    def _score_semantics(self, plate: List[Dict]) -> float:
        # Phase 3: Evaluate compatibility matrix
        matrix = NUTRITION_RULES.get("compatibility_matrix", {})
        if not matrix:
            return 100.0
            
        score = 100.0
        roles = [node['semantics'].get('meal_role') for node in plate if node.get('semantics', {}).get('meal_role')]
        
        # Check all unique pairs
        for i in range(len(roles)):
            for j in range(i + 1, len(roles)):
                role_a = roles[i]
                role_b = roles[j]
                
                # Check A -> B
                compat_a = matrix.get(role_a, {}).get(role_b, 1.0)
                # Check B -> A
                compat_b = matrix.get(role_b, {}).get(role_a, 1.0)
                
                # Use the lowest compatibility score
                compat = min(compat_a, compat_b)
                
                if compat < 1.0:
                    penalty = (1.0 - compat) * 100
                    score -= penalty
                elif compat > 1.0:
                    bonus = (compat - 1.0) * 50  # Cap bonus scaling to avoid massive inflation
                    score += bonus

        # Phase 7: Continuous compatibility scoring with rewards and penalties from YAML
        scoring_cfg = NUTRITION_RULES.get("compatibility_scoring", {})
        yaml_rewards = scoring_cfg.get("rewards", {})
        yaml_penalties = scoring_cfg.get("penalties", {})

        # Lowercase helper variables
        food_names_lower = [str(node.get("food_name", "")).lower() for node in plate]
        families_lower = [str(node.get("semantics", {}).get("dish_family") or node.get("semantics", {}).get("family", "")).lower() for node in plate]
        categories_lower = [str(node.get("semantics", {}).get("category", "")).lower() for node in plate]

        has_rice = any("rice" in name or "pulao" in name or "biryani" in name or "bath" in name for name in food_names_lower)
        has_sandwich = any("sandwich" in name or "burger" in name or "toast" in name or "wrap" in name or "roll" in name for name in food_names_lower)
        has_chapati = any("chapati" in name or "roti" in name or "phulka" in name or "naan" in name or "paratha" in name for name in food_names_lower)
        has_dal = any("dal" in name or "sambar" in name or "rasam" in name or "lentil" in name or family == "dal" for name, family in zip(food_names_lower, families_lower))
        has_veg = any(family in ("sabzi", "stir_fry", "poriyal", "dry_sabzi") or cat == "vegetables" for family, cat in zip(families_lower, categories_lower))
        has_idli = any("idli" in name for name in food_names_lower)
        has_sambar = any("sambar" in name for name in food_names_lower)
        has_poha = any("poha" in name for name in food_names_lower)
        has_curd = any("curd" in name or "yogurt" in name or "raita" in name or cat == "dairy" for name, cat in zip(food_names_lower, categories_lower))
        has_oats = any("oats" in name or "oat" in name for name in food_names_lower)
        has_fruit = any(cat == "fruits" or any(f in name for f in ("fruit", "apple", "banana", "berry", "berries", "mango", "orange", "pomegranate")) for name, cat in zip(food_names_lower, categories_lower))

        # Check Rewards
        if has_rice and has_dal and has_veg:
            score += yaml_rewards.get("rice_dal_veg", 15)
        if has_chapati and has_veg and has_dal:
            score += yaml_rewards.get("chapati_sabzi_dal", 15)
        if has_idli and has_sambar:
            score += yaml_rewards.get("idli_sambar", 10)
        if has_poha and has_curd:
            score += yaml_rewards.get("poha_curd", 10)
        if has_oats and has_fruit:
            score += yaml_rewards.get("oats_fruit", 10)

        # Check Penalties
        # 1. Rice + Sandwich
        if has_rice and has_sandwich:
            score -= yaml_penalties.get("rice_sandwich", 20)
        # 2. Milkshake + Curry
        has_milkshake = any("milkshake" in name or "smoothie" in name or "shake" in name for name in food_names_lower)
        has_curry = any("curry" in name or "gravy" in name or "dal" in name or family == "dal" for name, family in zip(food_names_lower, families_lower))
        if has_milkshake and has_curry:
            score -= yaml_penalties.get("milkshake_curry", 20)
        # 3. Two heavy starches
        starch_patterns = NUTRITION_RULES.get("compatibility", {}).get("starch_patterns", [])
        heavy_starch_count = 0
        for node in plate:
            name_l = node.get("food_name", "").lower()
            role = node.get("semantics", {}).get("meal_role", "")
            if role == "carb_base" or any(p in name_l for p in starch_patterns):
                heavy_starch_count += 1
        if heavy_starch_count >= 2:
            score -= yaml_penalties.get("two_heavy_starches", 15)
        # 4. Three dairy items
        dairy_count = 0
        for node in plate:
            name_l = node.get("food_name", "").lower()
            cat = node.get("semantics", {}).get("category", "").lower()
            if cat == "dairy" or any(d in name_l for d in ("milk", "curd", "yogurt", "paneer", "raita", "cheese")):
                dairy_count += 1
        if dairy_count >= 3:
            score -= yaml_penalties.get("three_dairy_items", 15)
        # 5. Soup, raita and salad together
        has_soup = any("soup" in name or "shorba" in name for name in food_names_lower)
        has_raita_item = any("raita" in name for name in food_names_lower)
        has_salad_item = any("salad" in name or "kachumber" in name or "kosambari" in name for name in food_names_lower)
        if has_soup and has_raita_item and has_salad_item:
            score -= yaml_penalties.get("soup_raita_salad_together", 15)

        return max(0.0, score)

    def _score_completeness(self, plate: List[Dict]) -> float:
        """
        Rewards plates that are structurally complete:
        - Base score from number of items
        - Bonus for having a vegetable component (+10)
        - Bonus for having a side dish/salad/raita/soup component (+10)
        - Bonus for having fruit or dairy (good for breakfast) (+5)
        These bonuses replaced the old hard blueprint fail, so good meals score higher.
        """
        length = len(plate)
        if length == 1:
            base = 45.0
        elif length == 2:
            base = 70.0
        elif 3 <= length <= 4:
            base = 85.0
        elif length == 5:
            base = 90.0
        else:
            base = 80.0

        # Structural bonuses (soft rewards instead of hard failures)
        has_vegetable = False
        has_side = False
        has_fruit_dairy = False

        for item in plate:
            cat = (item.get("semantics", {}).get("category", "") or "").lower()
            name_lower = (item.get("food_name", "") or "").lower()
            df = (item.get("semantics", {}).get("dish_family", "") or "").lower()

            if cat in ("vegetables", "leafy greens", "salad") or df in ("sabzi", "stir_fry", "poriyal"):
                has_vegetable = True
            if any(w in name_lower for w in ("salad", "raita", "kachumber", "kosambari", "chutney", "soup", "shorba", "papad")):
                has_side = True
            if cat in ("fruits",) or any(w in name_lower for w in ("fruit", "curd", "yogurt", "milk", "dairy")):
                has_fruit_dairy = True

        bonus = 0.0
        if has_vegetable:
            bonus += 8.0
        if has_side:
            bonus += 7.0
        if has_fruit_dairy:
            bonus += 5.0

        return min(100.0, base + bonus)

    def _score_realism(self, plate: List[Dict]) -> float:
        score = 100.0
        roles = [node['semantics'].get('meal_role') for node in plate]
        
        # Penalize weird combinations
        if roles.count('protein_main') > 1:
            score -= 40 # Two heavy mains
        if roles.count('beverage') > 1:
            score -= 30 # Two drinks
        if roles.count('salad') > 1:
            score -= 20 # Two salads
            
        # Penalize if it only contains side dishes
        if 'protein_main' not in roles and 'carb_base' not in roles and 'combo_meal' not in roles:
            score -= 50
            
        # Phase 3: Reward Food Group Diversity
        food_groups = [node['semantics'].get('category') for node in plate if node.get('semantics', {}).get('category')]
        unique_groups = len(set(food_groups))
        if unique_groups >= 3:
            score += 10
            
        # Texture/Temperature variety
        styles = [node['semantics'].get('cooking_style', 'Mixed') for node in plate]
        if 'Soup' in styles and 'Salad' in styles:
            score += 10  # Good contrast
        if styles.count('Dry') > 2:
            score -= 20  # Too dry
            
        # Satiety / Volume density heuristic
        # If total volume is high but calories are low, good for weight loss
        total_fiber = sum(node['nutrition'].get('fiber', 0) for node in plate)
        if total_fiber > 10:
            score += 10
        elif total_fiber == 0:
            score -= 10
            
        return max(0.0, min(100.0, score))

    def _score_variety(self, plate: List[Dict], current_day: int, meal_type: str = "unknown") -> float:
        if not self.variety_tracker:
            return 100.0
            
        shopping_efficiency_bonus = 0.0
        
        # Compute abstract Meal Signature
        sig_parts = []
        for item in plate:
            sem = item.get("semantics", {})
            cat = sem.get("category", "")
            cuisine = sem.get("cuisine", "")
            sig_parts.append(f"{cat}-{cuisine}")
        
        sig_parts.sort()
        signature = "|".join(sig_parts)
        
        # Get historical usage count
        usage_count = getattr(self.variety_tracker, "meal_signature_usage", {}).get(signature, 0)
        
        # Exponential Decay (Decay factor 1.5)
        decay_factor = 1.5
        score = 100.0 * math.exp(-usage_count / decay_factor)
        
        # Load penalties from config
        penalties_cfg = NUTRITION_RULES.get("variety_penalties", {})
        same_food_consec = float(penalties_cfg.get("same_food_consecutive_days", 15))
        same_food_second = float(penalties_cfg.get("same_food_second_occurrence", 25))
        same_food_third = float(penalties_cfg.get("same_food_third_occurrence", 50))
        same_family_wk = float(penalties_cfg.get("same_dish_family_per_week", 8))
        same_cuisine_wk = float(penalties_cfg.get("same_cuisine_per_week", 5))
        
        # Consecutive breakfast category penalty
        if meal_type.lower() == 'breakfast':
            current_cat = None
            for item in plate:
                if 'breakfast_category' in item.get('semantics', {}):
                    current_cat = item['semantics']['breakfast_category']
                    break
            if current_cat:
                yesterday_cat = self.variety_tracker.daily_breakfast_category.get(current_day - 1)
                if yesterday_cat == current_cat:
                    consec_penalty = float(penalties_cfg.get("same_breakfast_category_consecutive", 20))
                    score -= consec_penalty
                    
        # Cuisine repeat penalty
        cuisine = plate[0].get("semantics", {}).get("cuisine")
        if cuisine:
            cuisine_count = self.variety_tracker.weekly_cuisine_counts.get(cuisine, 0)
            if cuisine_count >= 3:
                score -= same_cuisine_wk
        
        for node in plate:
            family = node['semantics'].get('dish_family') or node['semantics'].get('family', 'other')
            family_clean = str(family).lower().strip()
            food_name = node.get('food_name', '')
            food_id = str(node.get('food_id', '')).lower().strip()
            
            # Continuous soft variety penalties
            # 1. Same food consecutive days
            last_day = self.variety_tracker.item_history.get(food_id)
            if last_day is not None and last_day == current_day - 1:
                score -= same_food_consec
                
            # 2. Same food repeats
            food_count = self.variety_tracker.weekly_food_counts.get(food_id, 0)
            if food_count == 1:
                score -= same_food_second
            elif food_count >= 2:
                score -= same_food_third
                
            # 3. Same dish family repeats
            if family_clean != "other":
                fam_count = self.variety_tracker.weekly_dish_family_counts.get(family_clean, 0)
                if fam_count >= 3:
                    score -= same_family_wk
            
            # Grocery Optimization: Raw ingredient reuse scoring
            ingredients = node.get('recipe', {}).get('ingredients', [])
            if not ingredients and 'ingredients' in node:
                ingredients = node.get('ingredients', [])
                
            raw_ings = []
            if not ingredients:
                raw_ings = [food_name.lower().strip()]
            else:
                raw_ings = [ing.get('item', '').lower().strip() if isinstance(ing, dict) else str(ing).lower().strip() for ing in ingredients]
                
            for ing in raw_ings:
                if not ing: continue
                # Check if ingredient was used in previous days
                past_used = False
                for d, foods in self.variety_tracker.daily_food_history.items():
                    if d < current_day:
                        if any(ing in f.lower() or f.lower() in ing for f in foods):
                            past_used = True
                            break
                
                if past_used:
                    shopping_efficiency_bonus += 10.0
                else:
                    score -= 5.0 # Penalty for introducing completely new raw ingredient
            
        return max(0.0, min(100.0, score))

    def _score_portion(self, plate: List[Dict]) -> float:
        score = 100.0
        for node in plate:
            unit = node.get('serving_unit', 'g')
            qty = float(node.get('serving_qty', 1.0))
            
            # Penalize absurd quantities for realistic units
            if unit in ('slice', 'slices') and qty > 4:
                score -= 20
            if unit in ('bowl', 'bowls') and qty > 3:
                score -= 30
            if unit in ('piece', 'pieces', 'unit') and qty > 6:
                score -= 20
                
        return max(0.0, min(100.0, score))
